# Generated by Django 3.1.4 on 2021-01-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conrtent',
            new_name='content',
        ),
    ]
